package ru.profitsw2000.core.drawable.utils

const val NO_ERROR = 0
const val LOW_FREQUENCY_UNDER_INPUT_ERROR = 0x01
const val LOW_FREQUENCY_ABOVE_INPUT_ERROR = 0x02
const val LOW_FREQ_HIGHER_THAN_HIGH_FREQ_INPUT_ERROR = 0x04
const val HIGH_FREQUENCY_UNDER_INPUT_ERROR = 0x08
const val HIGH_FREQUENCY_ABOVE_INPUT_ERROR = 0x10
const val MODULATION_PERIOD_ABOVE_INPUT_ERROR = 0x20
const val MODULATION_PERIOD_UNDER_INPUT_ERROR = 0x40
const val RESPONSE_PACKET_TIMEOUT_ERROR_CODE = 0x80
const val REGISTERS_CALCULATION_ERROR_CODE = 0x100
const val UNKNOWN_ERROR_CODE = 0x200