package ru.profitsw2000.core.drawable.utils

const val PACKET_SIZE_MAXIMUM = 0xA
const val WRITE_TO_TRANSMITTER_PACKET_ID = 0x01
const val WRITE_TO_SYNTHESIZER_PACKET_ID = 0x02
const val WRITE_TO_RECEIVER_PACKET_ID = 0x03
const val READ_FROM_TRANSMITTER_PACKET_ID = 0x04
const val READ_FROM_SYNTHESIZER_PACKET_ID = 0x05
const val READ_FROM_RECEIVER_PACKET_ID = 0x06
const val RCHM_DISS_OUTPUT_CONTROL_PACKET_ID = 0x07
const val RCHM_DISS_OUTPUT_SET_PACKET_ID = 0x08
const val WRITE_TO_EEPROM_PACKET_ID = 0x09
const val READ_FROM_EEPROM_REQUEST_PACKET_ID = 0x0A
const val READ_FROM_EEPROM_RESPONSE_PACKET_ID = 0x0B
const val READ_TEMPERATURE_REQUEST_PACKET_ID = 0x0C
const val READ_TEMPERATURE_RESPONSE_PACKET_ID = 0x0D